### ISSUE TITLE
Feature: Add Annotations to KeysetInfo_KeyInfo

### ISSUE THREAD

**Issue by theory** [tink-crypto/tink-go#14]
**Is your feature request related to a problem?**

Not a problem, no, but I think KeysetInfo_KeyInfo could benefit from additional information. As it is, users looking at a keyset (e.g., when serialized to JSON) have limited information about the keys. More info helps assist security assessments and the like without the need for separate record-keeping that can get out of sync with the actual key templates used.

**What sort of feature would you like to see?**

I'd like the ability for key templates (or keys?) to annotate KeysetInfo_KeyInfo contents with more than just the type ID, URL, status, and prefix type.

I made a Tink key template and key inspired by KMSEnvelopeAEADKeyTemplate. It simply encapsulates an AEAD key and a MAC key in a single key:

```proto
message BinkKey {
  uint32 version = 1;
  google.crypto.tink.KeyData aead_key_data = 2;
  google.crypto.tink.KeyData mac_key_data = 3;
}
```

It supports all the Tink aead and mac keys, and works great!

However, for serialization of the key with key info, I get this:

```json
{
  "encryptedKeyset": "...",
  "keysetInfo": {
    "primaryKeyId": 1075844356,
    "keyInfo": [
      {
        "typeUrl": "github.com/theory/bunk.key",
        "status": "DISABLED",
        "keyId": 723113882,
        "outputPrefixType": "TINK"
      },
      {
        "typeUrl": "github.com/theory/bunk.key",
        "status": "ENABLED",
        "keyId": 1075844356,
        "outputPrefixType": "TINK"
      }
    ]
  }
}
```

Which is not very informative. At a glance, the user cannot tell what kind of AEAD or MAC key is used by each key. A similar issue exists for KMSEnvelopeAEAD keys: you can't tell what kind of AEAD key is used to encrypt the data.

I'd like to request a way to somehow annotate KeysetInfo_KeyInfo with additional information, so the output could be designed for my keys to look more like this:

```json
{
  "encryptedKeyset": "...",
  "keysetInfo": {
    "primaryKeyId": 1075844356,
    "keyInfo": [
      {
        "typeUrl": "github.com/theory/bunk.key",
        "status": "DISABLED",
        "keyId": 723113882,
        "outputPrefixType": "TINK",
        "details": {
          "aeadKeyTypeUrl": "type.googleapis.com/google.crypto.tink.AesGcmKey",
          "macKeyTypeUrl": "type.googleapis.com/google.crypto.tink.HmacKey"
        }
      },
      {
        "typeUrl": "github.com/theory/bunk.key",
        "status": "ENABLED",
        "keyId": 1075844356,
        "outputPrefixType": "TINK",
        "details": {
          "aeadKeyTypeUrl": "type.googleapis.com/google.crypto.tink.XChaCha20Poly1305Key",
          "macKeyTypeUrl": "type.googleapis.com/google.crypto.tink.AesCmacKey"
        }
      }
    ]
  }
}
```

Or perhaps with even more detail:

```json
{
  "encryptedKeyset": "...",
  "keysetInfo": {
    "primaryKeyId": 1075844356,
    "keyInfo": [
      {
        "typeUrl": "github.com/theory/bunk.key",
        "status": "DISABLED",
        "keyId": 723113882,
        "outputPrefixType": "TINK",
        "details": {
          "aeadKeyTypeUrl": "type.googleapis.com/google.crypto.tink.AesGcmKey",
          "aeadKeyAlgorithm": "AES256GCMNoPrefix",
          "macKeyTypeUrl": "type.googleapis.com/google.crypto.tink.HmacKey",
          "macKeyAlgorithm": "HMACSHA256Tag256"
        }
      }
    ]
  }
}
```

I could imagine this being useful for KMSEnvelopeAEAD keys, too.

**Have you considered any alternative solutions?**

I can write my own serialization layer that encrypts the keyset and puts in its own key info. But it seems unnecessarily duplicative (is that a word?), and also a bit more error prone from a security perspective. Tink already has the KMS encryption of the keyset configured exactly right, why copy/paste it and then lose any improvements/fixes later on?

**Would you like to add additional context?**

Thanks for Tink!

**Comment by theory** [comment]
Thanks for the reply! This sounds very promising. Is there some way to store parameters in the key today, so that once that feature lands they will be displayable?

**Comment by theory** [comment]
But where are the parameters stored?

**Comment by tholenst** [comment]
The key protos have enough information to get the parameters out. (The parameters are the same as the key template).

For example, in the serialization, a AES GCM Key looks like this:

message AesGcmKey {
  uint32 version = 1;
  bytes key_value = 3;
}

The parameters of a AES GCM Key looks like this:

message AesGcmKeyFormat {
  uint32 key_size = 2;
  uint32 version = 3;
}

This is embedded into a KeyTemplate proto.

One can compute the AesGcmKeyFormat from the AesGcmKey proto.

**Comment by theory** [comment]
I'll have to poke around the implementation, but I'm little confused here. AFAIK the `AesGcmKey` is the value stored in the keyset, not the `AesGcmKeyFormat`. Given an `AesGcmKey`, how do you know what `AesGcmKeyFormat` to load? Or is the key template also stored in the keyset and I just haven't noticed it yet.

**Comment by theory** [comment]
Yes. Looking at the AesGcmKey example, I suppose it knows what the configuration values were based on the version? Cause that's the only bit of info I see in the key other than the key material.

**Comment by theory** [comment]
I'm afraid there's not much I can make of it one way or another. Could you maybe create a little sample project, zip it up, and attach it here? Important to bundle it into an archive to preserve the encodings. I could try to take it and spin up a GitHub workflow that uses an Oracle Docker image to replicate it. Unless, of course, you could do that :-)

**Comment by tholenst** [comment]
Ah sorry, I see I'm still being confusing.

Given a Key you can simply compute key_size in the format as key_value.size().

Unfortunately, I don't have time to create sample projects for this.

**Comment by theory** [comment]
Oooh, 🤦🏻 right I should have thought of that!

**Comment by theory** [comment]
I got pretty far down the line adding parameters to my key format and key proto, and updated the manager to copy them into the key primitive. This lets me implement a custom writer that emits key parameters instead of the default KeyInfo.

It works beautifully except for one thing: the resulting info includes only enabled keys. This is because the `Primitives()` method on the keyset handle returns only enabled keys:

https://github.com/tink-crypto/tink-java/blob/b0acb55878a53e397a1b39a9f74babf5cf315f62/src/main/java/com/google/crypto/tink/prf/HkdfPrfKey.java#L94-L96

This makes perfect sense for keys loaded into a keyset used for encryption and encryption! But as there is no `GetAt` method on the Go Keyset handle, there is no way to iterate through all enabled and disabled keys. One can only get at keyset info.

So I'm wondering if it'd make sense to add a method like `Primitives()` but returns all primitives in the set, not just enabled primitives.
