### ISSUE TITLE
Feature: Where to find canonical proto defintions?

### ISSUE THREAD

**Issue by mikedanese** [tink-crypto/tink-go#15]
Where is the canonical location for tink proto definitions?

* tink-go only has the generated defs
* https://github.com/tink-crypto/tink says that it will be archived
* https://github.com/tink-crypto/tink-cc has the protos but they are using the old import path: https://github.com/tink-crypto/tink-cc/blob/208fc56f58d101b723d5774a935c4a72c08f5e17/proto/aes_cmac.proto#L23. github.com/google/tink/go/proto/aes_cmac_go_proto instead of github.com/google/tink-crypto/tink-go/v2/proto/aes_cmac_go_proto.

I would love to have the canonical proto defs so that I can write my own proto APIs that use tink types, and have client libraries that are compatible with this go module.

**Comment by juergw** [comment]
Sorry we haven't replied to this yet. Yes, I agree that we should fix this.

**Comment by morambro** [comment]
Proto definitions were added in e8b7b7be52b667f20a5627db60ffff151dd00515
