### ISSUE TITLE
Extract PublicKey from signing keyset

### ISSUE THREAD

**Issue by salrashid123** [tink-crypto/tink-go#18]
I'm trying to extract the RSA public key used when creating a signature using tink but can't seem to find any easy way to do that

For example, in the following, i'm creating a public/private keyset

* `type.googleapis.com/google.crypto.tink.RsaSsaPkcs1PrivateKey`
* `type.googleapis.com/google.crypto.tink.RsaSsaPkcs1PublicKey`

and what i'd like to do in the last step is to extract out the actual RSA public as [rsa.PublicKey](https://pkg.go.dev/crypto/rsa#PublicKey)

```golang
package main

import (
	"bytes"
	"encoding/json"
	"log"

	"github.com/tink-crypto/tink-go/v2/insecurecleartextkeyset"
	"github.com/tink-crypto/tink-go/v2/keyset"
	"github.com/tink-crypto/tink-go/v2/signature"

)

const ()

func main() {

	priv_kh, _ := keyset.NewHandle(signature.RSA_SSA_PKCS1_3072_SHA256_F4_RAW_Key_Template())

	buf := new(bytes.Buffer)
	w := keyset.NewJSONWriter(buf)
	_ = insecurecleartextkeyset.Write(priv_kh, w)

	var prettyJSON bytes.Buffer
	_ = json.Indent(&prettyJSON, buf.Bytes(), "", "\t")

	privateJSONKeyset := prettyJSON.String()
	log.Printf("Private Keyset: %s\n", privateJSONKeyset)

	pub_kh, _ := priv_kh.Public()

	pubuf := new(bytes.Buffer)
	pubw := keyset.NewJSONWriter(pubuf)
	_ = insecurecleartextkeyset.Write(pub_kh, pubw)

	var pubPrettyJSON bytes.Buffer
	_ = json.Indent(&pubPrettyJSON, pubuf.Bytes(), "", "\t")

	publicJSONKeyset := pubuf.String()
	log.Printf("Public Keyset: %s\n", publicJSONKeyset)
}
```

the only way i could make this all work is spelunking through the proto as shown here:

https://gist.github.com/salrashid123/0e42a5761d02f2f9b6fd2e3d60fc864f#file-tinkrsa-go-L95

---

am i missing some easy way to do all this if i want to verify a signature externally?

**Comment by Muzosh** [comment]
Hello @salrashid123, may I ask why did you close this issue? I realize it has been a long time since. Perhaps your workaround from the gist was enough?

**Comment by salrashid123** [comment]
@Muzosh i basically just  did it on my own  

* https://github.com/salrashid123/tink-keyset-util

**Comment by Muzosh** [comment]
Hi @morambro, thanks for the info. I actually tried it myself for RSA, ED25519, and ECDSA keys.

I wonder, is it by Tink's choice to not make it easy to convert from/to Go's key types? (By "not easy" I mean having to access parameters myself and work with that to instantiate a Go std/crypto type) Do you see something like that integrated in tink-go itself in the future?

Also, we are talking about exporting tink keys here. What about importing? I'm sure it can perhaps be done by similar "hacking away", but official API to just create tink verifier from `crypto/rsa.PublicKey` would be super nice as there are many sources a public key can come from.

**Comment by morambro** [comment]
> I wonder, is it by Tink's choice to not make it easy to convert from/to Go's key types? (By "not easy" I mean having to access parameters myself and work with that to instantiate a Go std/crypto type) Do you see something like that integrated in tink-go itself in the future?

Ideally one would never have to deal with keys at the "low level" and use Tink primitives from the Keyset; this is what Tink tries to encourage. Also, we try to keep a tradeoff between keeping the API surface small and adding more utility functions. Going from an `rsassapcks1.PublicKey` to an `rsa.PublicKey` is fairly simple:
```go
func TinkRSASSAPCKS1PublicKeyToStdCryptoPublicKey(tinkPublicKey *rsassapkcs1.PublicKey) &rsa.PublicKey {
	return &rsa.PublicKey{
		N: new(big.Int).SetBytes(tinkPublicKey.Modulus()),
		E: tinkPublicKey.Parameters().(*rsassapkcs1.Parameters).PublicExponent(),
	}
}
```

But I see that for others such as ECDSA this is more complex.

We may consider adding some utility functions to help with more complex cases.

> Also, we are talking about exporting tink keys here. What about importing? I'm sure it can perhaps be done by similar "hacking away", but official API to just create tink verifier from `crypto/rsa.PublicKey` would be super nice as there are many sources a public key can come from.

For some primitives we have `subtle` APIs like https://github.com/tink-crypto/tink-go/blob/bf77f8e08e14e872715b3c125d70dc3a0053e7ac/signature/subtle/ecdsa_verifier.go#L47
For RSA these are currently internal only.

In general, one currently has to do something like the following (this is HMAC, but for RSA signing is going to be similar): https://github.com/tink-crypto/tink-go/blob/bf77f8e08e14e872715b3c125d70dc3a0053e7ac/mac/hmac/hmac_test.go#L70-L106

Something in between which would allow to skip the creation of the keyset, but still requires to create a Tink key, is https://github.com/tink-crypto/tink-go/blob/bf77f8e08e14e872715b3c125d70dc3a0053e7ac/signature/rsassapkcs1/verifier.go#L41
This is currently internal, but we may consider exporting it.
