### ISSUE TITLE
Guidance on storing keyset.Handle

### ISSUE THREAD

**Issue by shakeelrao** [tink-crypto/tink-go#20]
Hi there! 

Apologies in advance if this isn't the right forum to ask for guidance, but I was looking for guidance on storing `keyset.Handle`. 

Is it advisable to create and destroy the handle "on-demand" (i.e. when needed) or to simply compute the handle once and store a reference to it? In other words: is it safe to have the handle stored in-memory for the lifetime of a process?

Thanks!

**Comment by cindylindeed** [comment]
Generally, you want to destroy the `keyset.Handle` when you no longer need it. More specifically, the answer here depends on your execution environment / threat model / how sensitive the key material is, which we cannot comment on.
